network:
  renderer: networkd
  ethernets:
    enp0s3:
      addresses: [172.16.29.118/16]             #Inserire l'indirizzo desiderato con la relativa netmask
      gateway4: 172.16.1.7                      #Inserire l'indirizzo del gateway predefinito
      nameservers:
        search: [virtual.marconi]               #Inserire altre opzioni
        addresses: [172.16.1.8, 172.16.1.10]    #Inserire il DNS
  version: 2
