# This is the network config written by 'subiquity'
network:
  renderer: networkd
  ethernets:
    enp0s3:
      addresses: [172.16.29.118/16]
      gateway4: 172.16.1.7
      nameservers:
        search: [virtual.marconi]
        addresses: [172.16.1.8, 172.16.1.10]
  version: 2
